version: '3.8'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=zenbit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=28081988
    ports:
      - '5432:5432'
    volumes:
    - ./postgres_data:/var/lib/postgresql